apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-db
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: nfsva.stk.svc.ulaval.ca
    path: /ul-pca-pr-valeria-ul-prj-influence-dv
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: jupyterhub-db
    namespace: coda19-jupyterhub