---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: jupyterhub-deployer
  annotations:
    openshift.io/display-name: JupyterHub
    description: Template for deploying a JupyterHub instance.
    iconClass: icon-python
    tags: python,jupyter,jupyterhub
parameters:
- name: APPLICATION_NAME
  value: jupyterhub
  required: true
- name: JUPYTERHUB_IMAGE
  value: jupyterhub:3.4.0
  required: true
- name: NOTEBOOK_IMAGE
  value: s2i-minimal-notebook:3.6
  required: true
- name: JUPYTERHUB_CONFIG
  value: ''
  required: false
- name: JUPYTERHUB_ENVVARS
  value: ''
  required: false
- name: DATABASE_PASSWORD
  required: true
- name: COOKIE_SECRET
  generate: expression
  from: "[a-f0-9]{32}"
  required: true
- name: JUPYTERHUB_MEMORY
  description: Amount of memory available to JupyterHub.
  value: 512Mi
  required: true
- name: NOTEBOOK_MEMORY
  description: Amount of memory available to each notebook.
  value: 512Mi
  required: true
- name: JUPYTERHUB_OAUTH_CLIENT_ID
  required: true
- name: JUPYTERHUB_OAUTH_CLIENT_SECRET
  required: true
- name: JUPYTERHUB_OAUTH_CLIENT_URL
  required: true
- name: JUPYTERHUB_CRYPT_KEY
  required: true
- name: NOTEBOOK_USER_PERSISTENT_VOLUME
  required: true
- name: JUPYTERHUB_URL
  required: true
- name: CODA19_JUPYTERHUB_FQDN
  displayName: Custom https Route Hostname
  description: >-
    Custom hostname for https service route. Leave blank for default hostname,
    e.g.: <application-name>-<namespace>.<default-domain-suffix>
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-cfg"
    labels:
      app: "${APPLICATION_NAME}"
  data:
    jupyterhub_config.py: "${JUPYTERHUB_CONFIG}"
    jupyterhub_config.sh: "${JUPYTERHUB_ENVVARS}"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-hub"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${APPLICATION_NAME}"}}'
      serviceaccounts.openshift.io/oauth-redirecturi.first: hub/oauth_callback
      serviceaccounts.openshift.io/oauth-want-challenges: 'false'
- kind: RoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}-edit"
    labels:
      app: "${APPLICATION_NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${APPLICATION_NAME}-hub"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - wait-for-database
        - jupyterhub
        from:
          kind: ImageStreamTag
          name: "${JUPYTERHUB_IMAGE}"
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    template:
      metadata:
        annotations:
          alpha.image.policy.openshift.io/resolve-names: "*"
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        serviceAccountName: "${APPLICATION_NAME}-hub"
        initContainers:
        - name: wait-for-database
          image: "${JUPYTERHUB_IMAGE}"
          command:
          - wait-for-database
          resources:
            limits:
              memory: "${JUPYTERHUB_MEMORY}"
          env:
          - name: JUPYTERHUB_DATABASE_PASSWORD
            value: "${DATABASE_PASSWORD}"
          - name: JUPYTERHUB_DATABASE_HOST
            value: "${APPLICATION_NAME}-db"
          - name: JUPYTERHUB_DATABASE_NAME
            value: postgres
        containers:
        - name: jupyterhub
          image: "${JUPYTERHUB_IMAGE}"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: "${JUPYTERHUB_MEMORY}"
          env:
          - name: APPLICATION_NAME
            value: "${APPLICATION_NAME}"
          - name: JUPYTERHUB_NOTEBOOK_IMAGE
            value: "${NOTEBOOK_IMAGE}"
          - name: JUPYTERHUB_NOTEBOOK_MEMORY
            value: "${NOTEBOOK_MEMORY}"
          - name: JUPYTERHUB_DATABASE_PASSWORD
            value: "${DATABASE_PASSWORD}"
          - name: JUPYTERHUB_DATABASE_HOST
            value: "${APPLICATION_NAME}-db"
          - name: JUPYTERHUB_DATABASE_NAME
            value: postgres
          - name: JUPYTERHUB_COOKIE_SECRET
            value: "${COOKIE_SECRET}"
          - name: JUPYTERHUB_OAUTH_CLIENT_ID
            value: "${JUPYTERHUB_OAUTH_CLIENT_ID}"
          - name: JUPYTERHUB_OAUTH_CLIENT_SECRET
            value: "${JUPYTERHUB_OAUTH_CLIENT_SECRET}"
          - name: JUPYTERHUB_OAUTH_CLIENT_URL
            value: "${JUPYTERHUB_OAUTH_CLIENT_URL}"
          - name: JUPYTERHUB_CRYPT_KEY
            value: "${JUPYTERHUB_CRYPT_KEY}"
          - name: NOTEBOOK_USER_PERSISTENT_VOLUME
            value: "${NOTEBOOK_USER_PERSISTENT_VOLUME}"
          - name: JUPYTERHUB_URL
            value: "${JUPYTERHUB_URL}"
          volumeMounts:
          - name: config
            mountPath: "/opt/app-root/configs"
        volumes:
        - name: config
          configMap:
            name: "${APPLICATION_NAME}-cfg"
            defaultMode: 420
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    host: "${CODA19_JUPYTERHUB_FQDN}"
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect